version: '3.1' 

services:

  db:
    container_name: db
    image: mysql:5.7.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
